version: "3.8"

services:
  built-mysql:
    command: >
      mysqld
        --character-set-server=utf8mb4
        --collation-server=utf8mb4_unicode_ci
        --sql-mode NO_ENGINE_SUBSTITUTION
    container_name: built-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    image: mysql:5.7
    networks:
      - built-network
    ports:
      - 3306:3306
    volumes:
      - ./docker/provision/mysql/init:/docker-entrypoint-initdb.d
      - built-mysql-volume:/var/lib/mysql

  built-budgets:
    build:
      context: built-budgets
    container_name: built-budgets
    environment:
      FLASK_APP: autoapp
      FLASK_DEBUG: 1
      FLASK_ENV: development
      FLASK_RUN_HOST: "0.0.0.0"
      FLASK_RUN_PORT: "80"
      MYSQL_DATABASE: budgets
      MYSQL_HOST: built-mysql
      MYSQL_PASSWORD: password
      MYSQL_PORT: 3306
      MYSQL_USER: built
    image: built-budgets:latest
    networks:
      - built-network
    ports:
      - 5001:80
    volumes:
      - ./built-budgets:/opt/src:rw

  built-draws:
    build:
      context: built-draws
    container_name: built-draws
    environment:
      FLASK_APP: autoapp
      FLASK_DEBUG: 1
      FLASK_ENV: development
      FLASK_RUN_HOST: "0.0.0.0"
      FLASK_RUN_PORT: "80"
      MYSQL_DATABASE: draws
      MYSQL_HOST: built-mysql
      MYSQL_PASSWORD: password
      MYSQL_PORT: 3306
      MYSQL_USER: built
    image: built-draws:latest
    networks:
      - built-network
    ports:
      - 5002:80
    volumes:
      - ./built-draws:/opt/src:rw

networks:
  built-network:
    name: built-network

volumes:
  built-mysql-volume:
    name: built-mysql-volume
